insert into public.dependency (dependency_code, dependency_description, dependency_name, dependency_category,
                               basic_dependency)
values ('runtimeOnly ''com.oracle.database.jdbc:ojdbc11''', 'A JDBC driver that provides access to Oracle.',
        'Oracle Driver', 'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-mongodb''',
        'Store data in flexible, JSON-like documents, meaning fields can vary from document to document and data structure can be changed over time.',
        'Spring Data MongoDB', 'NOSQL', false),
       ('implementation ''org.apache.kafka:kafka-streams''',
        'Building stream processing applications with Apache Kafka Streams.', 'Spring for Apache Kafka Streams',
        'MESSAGING', false),
       ('testImplementation ''org.projectlombok:lombok:1.18.26''
compileOnly ''org.projectlombok:lombok''
annotationProcessor ''org.projectlombok:lombok''
testAnnotationProcessor ''org.projectlombok:lombok''',
        'Java annotation library which helps to reduce boilerplate code.', 'Lombok', 'DEVELOPER TOOLS', true),
       ('implementation ''org.springframework.boot:spring-boot-starter-mustache''',
        'Logic-less templates for both web and standalone environments. There are no if statements, else clauses, or for loops. Instead there are only tags.',
        'Mustache', 'TEMPLATE ENGINES', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-oauth2-authorization-server''',
        'Spring Boot integration for Spring Authorization Server.', 'OAuth2 Authorization Server', 'SECURITY', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-thymeleaf''',
        'A modern server-side Java template engine for both web and standalone environments. Allows HTML to be correctly displayed in browsers and as static prototypes.',
        'Thymeleaf', 'TEMPLATE ENGINES', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-cassandra''',
        'A free and open-source, distributed, NoSQL database management system that offers high-scalability and high-performance.',
        'Spring Data for Apache Cassandra', 'NOSQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-cassandra-reactive''',
        'Access Cassandra NoSQL Database in a reactive fashion.', 'Spring Data Reactive for Apache Cassandra', 'NOSQL',
        false),
       ('implementation ''org.springframework.boot:spring-boot-starter-oauth2-resource-server''',
        'Spring Boot integration for Spring Security''s OAuth2 resource server features.', 'OAuth2 Resource Server',
        'SECURITY', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-redis''',
        'Advanced and thread-safe Java Redis client for synchronous, asynchronous, and reactive usage. Supports Cluster, Sentinel, Pipelining, Auto-Reconnect, Codecs and much more.',
        'Spring Data Redis (Access+Driver)', 'NOSQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-activemq''',
        'Spring JMS support with Apache ActiveMQ ''Classic''.', 'Spring for Apache ActiveMQ 5', 'MESSAGING', false),
       ('implementation ''org.apache.camel.springboot:camel-spring-boot-starter:4.5.0''',
        'Apache Camel is an open source integration framework that empowers you to quickly and easily integrate various systems consuming or producing data.',
        'Apache Camel', 'MESSAGING', false),
       ('implementation ''org.springframework.kafka:spring-kafka''',
        'Publish, subscribe, store, and process streams of records.', 'Spring for Apache Kafka', 'MESSAGING', false),
       ('developmentOnly ''org.springframework.boot:spring-boot-devtools''',
        'Provides fast application restarts, LiveReload, and configurations for enhanced development experience.',
        'Spring Boot DevTools', 'DEVELOPER TOOLS', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-rsocket''',
        'RSocket.io applications with Spring Messaging and Netty.', 'RSocket', 'MESSAGING', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-mail''',
        'Send email using Java Mail and Spring Framework''s JavaMailSender.', 'Java Mail Sender', 'I/O', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-jpa''',
        'Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.', 'Spring Data JPA',
        'SQL', true),
       ('implementation ''org.springframework.boot:spring-boot-starter-quartz''', 'Schedule jobs using Quartz.',
        'Quartz Scheduler', 'I/O', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-elasticsearch''',
        'A distributed, RESTful search and analytics engine with Spring Data Elasticsearch.',
        'Spring Data Elasticsearch (Access+Driver)', 'NOSQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-amqp''',
        'Gives your applications a common platform to send and receive messages, and your messages a safe place to live until received.',
        'Spring for RabbitMQ', 'MESSAGING', false),
       ('runtimeOnly ''com.microsoft.sqlserver:mssql-jdbc''',
        'A JDBC and R2DBC driver that provides access to Microsoft SQL Server and Azure SQL Database from any Java application.',
        'MS SQL Server Driver', 'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-security''',
        'Highly customizable authentication and access-control framework for Spring applications.', 'Spring Security',
        'SECURITY', false),
       ('implementation ''org.springframework.amqp:spring-rabbit-stream''',
        'Building stream processing applications with RabbitMQ.', 'Spring for RabbitMQ Streams', 'MESSAGING', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-ldap''',
        'Makes it easier to build Spring based applications that use the Lightweight Directory Access Protocol.',
        'Spring LDAP', 'SECURITY', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-oauth2-client''',
        'Spring Boot integration for Spring Security''s OAuth2/OpenID Connect client features.', 'OAuth2 Client',
        'SECURITY', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-r2dbc''',
        'Provides Reactive Relational Database Connectivity to persist data in SQL stores using Spring Data in reactive applications.',
        'Spring Data R2DBC', 'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-websocket''',
        'Build Servlet-based WebSocket applications with SockJS and STOMP.', 'WebSocket', 'MESSAGING', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-integration''',
        'Adds support for Enterprise Integration Patterns. Enables lightweight messaging and supports integration with external systems via declarative adapters.',
        'Spring Integration', 'MESSAGING', false),
       ('runtimeOnly ''org.mariadb.jdbc:mariadb-java-client''', 'MariaDB JDBC and R2DBC driver.', 'MariaDB Driver',
        'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-validation''',
        'Bean Validation with Hibernate validator.', 'Validation', 'I/O', true),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-mongodb-reactive''',
        'Provides asynchronous stream processing with non-blocking back pressure for MongoDB.',
        'Spring Data Reactive MongoDB', 'NOSQL', false),
       ('runtimeOnly ''com.mysql:mysql-connector-j''', 'MySQL JDBC driver.', 'MySQL Driver', 'SQL', true),
       ('runtimeOnly ''org.postgresql:postgresql''',
        'A JDBC and R2DBC driver that allows Java programs to connect to a PostgreSQL database using standard, database independent Java code.',
        'PostgreSQL Driver', 'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-redis-reactive''',
        'Access Redis key-value data stores in a reactive fashion with Spring Data Redis.',
        'Spring Data Reactive Redis', 'NOSQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-jdbc''',
        'Database Connectivity API that defines how a client may connect and query a database.', 'JDBC API', 'SQL',
        false),
       ('implementation ''org.springframework.boot:spring-boot-starter-data-jdbc''',
        'Persist data in SQL stores with plain JDBC using Spring Data.', 'Spring Data JDBC', 'SQL', false),
       ('implementation ''org.springframework.boot:spring-boot-starter-batch''',
        'Batch applications with transactions, retry/skip and chunk based processing.', 'Spring Batch', 'I/O', false),
       ('implementation ''org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3''',
        'Persistence framework with support for custom SQL, stored procedures and advanced mappings. MyBatis couples objects with stored procedures or SQL statements using a XML descriptor or annotations.',
        'MyBatis Framework', 'SQL', false),
       ('runtimeOnly ''com.h2database:h2''',
        'Provides a fast in-memory database that supports JDBC API and R2DBC access, with a small (2mb) footprint. Supports embedded and server modes as well as a browser based console application.',
        'H2 Database', 'SQL', false),
       ('implementation ''org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2''
implementation ''org.springdoc:springdoc-openapi-starter-common:2.0.2''
implementation ''org.springdoc:springdoc-openapi-ui:1.6.15''',
        'springdoc-openapi java library helps to automate the generation of API documentation using spring boot projects.',
        'Swagger - Spring Doc', 'DEVELOPER TOOLS', true);