INSERT INTO dependency (dependency_name, dependency_description, dependency_category, dependency_code)
VALUES ('Thymeleaf',
        'A modern server-side Java template engine for both web and standalone environments. Allows HTML to be correctly displayed in browsers and as static prototypes.',
        'TEMPLATE ENGINES', 'implementation ''org.springframework.boot:spring-boot-starter-thymeleaf'''),
       ('Mustache',
        'Logic-less templates for both web and standalone environments. There are no if statements, else clauses, or for loops. Instead there are only tags.',
        'TEMPLATE ENGINES', 'implementation ''org.springframework.boot:spring-boot-starter-mustache'''),
       ('Spring Security', 'Highly customizable authentication and access-control framework for Spring applications.',
        'SECURITY', 'implementation ''org.springframework.boot:spring-boot-starter-security'''),
       ('OAuth2 Client', 'Spring Boot integration for Spring Security''s OAuth2/OpenID Connect client features.',
        'SECURITY', 'implementation ''org.springframework.boot:spring-boot-starter-oauth2-client'''),
       ('OAuth2 Authorization Server', 'Spring Boot integration for Spring Authorization Server.', 'SECURITY',
        'implementation ''org.springframework.boot:spring-boot-starter-oauth2-authorization-server'''),
       ('OAuth2 Resource Server', 'Spring Boot integration for Spring Security''s OAuth2 resource server features.',
        'SECURITY', 'implementation ''org.springframework.boot:spring-boot-starter-oauth2-resource-server'''),
       ('Spring LDAP',
        'Makes it easier to build Spring based applications that use the Lightweight Directory Access Protocol.',
        'SECURITY', 'implementation ''org.springframework.boot:spring-boot-starter-data-ldap'''),
       ('JDBC API', 'Database Connectivity API that defines how a client may connect and query a database.', 'SQL',
        'implementation ''org.springframework.boot:spring-boot-starter-jdbc'''),
       ('Spring Data JPA', 'Persist data in SQL stores with Java Persistence API using Spring Data and Hibernate.',
        'SQL', 'implementation ''org.springframework.boot:spring-boot-starter-data-jpa'''),
       ('Spring Data JDBC', 'Persist data in SQL stores with plain JDBC using Spring Data.', 'SQL',
        'implementation ''org.springframework.boot:spring-boot-starter-data-jdbc'''),
       ('Spring Data R2DBC',
        'Provides Reactive Relational Database Connectivity to persist data in SQL stores using Spring Data in reactive applications.',
        'SQL', 'implementation ''org.springframework.boot:spring-boot-starter-data-r2dbc'''),
       ('MyBatis Framework',
        'Persistence framework with support for custom SQL, stored procedures and advanced mappings. MyBatis couples objects with stored procedures or SQL statements using a XML descriptor or annotations.',
        'SQL', 'implementation ''org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.3'''),
       ('H2 Database',
        'Provides a fast in-memory database that supports JDBC API and R2DBC access, with a small (2mb) footprint. Supports embedded and server modes as well as a browser based console application.',
        'SQL', 'runtimeOnly ''com.h2database:h2'''),
       ('MariaDB Driver', 'MariaDB JDBC and R2DBC driver.', 'SQL',
        'runtimeOnly ''org.mariadb.jdbc:mariadb-java-client'''),
       ('MS SQL Server Driver',
        'A JDBC and R2DBC driver that provides access to Microsoft SQL Server and Azure SQL Database from any Java application.',
        'SQL', 'runtimeOnly ''com.microsoft.sqlserver:mssql-jdbc'''),
       ('MySQL Driver', 'MySQL JDBC driver.', 'SQL', 'runtimeOnly ''com.mysql:mysql-connector-j'''),
       ('Oracle Driver', 'A JDBC driver that provides access to Oracle.', 'SQL',
        'runtimeOnly ''com.oracle.database.jdbc:ojdbc11'''),
       ('PostgreSQL Driver',
        'A JDBC and R2DBC driver that allows Java programs to connect to a PostgreSQL database using standard, database independent Java code.',
        'SQL', 'runtimeOnly ''org.postgresql:postgresql'''),
       ('Spring Data Redis (Access+Driver)',
        'Advanced and thread-safe Java Redis client for synchronous, asynchronous, and reactive usage. Supports Cluster, Sentinel, Pipelining, Auto-Reconnect, Codecs and much more.',
        'NOSQL', 'implementation ''org.springframework.boot:spring-boot-starter-data-redis'''),
       ('Spring Data Reactive Redis',
        'Access Redis key-value data stores in a reactive fashion with Spring Data Redis.', 'NOSQL',
        'implementation ''org.springframework.boot:spring-boot-starter-data-redis-reactive'''),
       ('Spring Data MongoDB',
        'Store data in flexible, JSON-like documents, meaning fields can vary from document to document and data structure can be changed over time.',
        'NOSQL', 'implementation ''org.springframework.boot:spring-boot-starter-data-mongodb'''),
       ('Spring Data Reactive MongoDB',
        'Provides asynchronous stream processing with non-blocking back pressure for MongoDB.', 'NOSQL',
        'implementation ''org.springframework.boot:spring-boot-starter-data-mongodb-reactive'''),
       ('Spring Data Elasticsearch (Access+Driver)',
        'A distributed, RESTful search and analytics engine with Spring Data Elasticsearch.', 'NOSQL',
        'implementation ''org.springframework.boot:spring-boot-starter-data-elasticsearch'''),
       ('Spring Data for Apache Cassandra',
        'A free and open-source, distributed, NoSQL database management system that offers high-scalability and high-performance.',
        'NOSQL', 'implementation ''org.springframework.boot:spring-boot-starter-data-cassandra'''),
       ('Spring Data Reactive for Apache Cassandra', 'Access Cassandra NoSQL Database in a reactive fashion.', 'NOSQL',
        'implementation ''org.springframework.boot:spring-boot-starter-data-cassandra-reactive'''),
       ('Spring Integration',
        'Adds support for Enterprise Integration Patterns. Enables lightweight messaging and supports integration with external systems via declarative adapters.',
        'MESSAGING', 'implementation ''org.springframework.boot:spring-boot-starter-integration'''),
       ('Spring for RabbitMQ',
        'Gives your applications a common platform to send and receive messages, and your messages a safe place to live until received.',
        'MESSAGING', 'implementation ''org.springframework.boot:spring-boot-starter-amqp'''),
       ('Spring for Apache Kafka', 'Publish, subscribe, store, and process streams of records.', 'MESSAGING',
        'implementation ''org.springframework.kafka:spring-kafka'''),
       ('Spring for Apache Kafka Streams', 'Building stream processing applications with Apache Kafka Streams.',
        'MESSAGING', 'implementation ''org.apache.kafka:kafka-streams'''),
       ('Spring for Apache ActiveMQ 5', 'Spring JMS support with Apache ActiveMQ ''Classic''.', 'MESSAGING',
        'implementation ''org.springframework.boot:spring-boot-starter-activemq'''),
       ('WebSocket', 'Build Servlet-based WebSocket applications with SockJS and STOMP.', 'MESSAGING',
        'implementation ''org.springframework.boot:spring-boot-starter-websocket'''),
       ('RSocket', 'RSocket.io applications with Spring Messaging and Netty.', 'MESSAGING',
        'implementation ''org.springframework.boot:spring-boot-starter-rsocket'''),
       ('Apache Camel',
        'Apache Camel is an open source integration framework that empowers you to quickly and easily integrate various systems consuming or producing data.',
        'MESSAGING', 'implementation ''org.apache.camel.springboot:camel-spring-boot-starter:4.5.0'''),
       ('Spring for RabbitMQ Streams', 'Building stream processing applications with RabbitMQ.', 'MESSAGING',
        'implementation ''org.springframework.amqp:spring-rabbit-stream'''),
       ('Spring Batch', 'Batch applications with transactions, retry/skip and chunk based processing.', 'I/O',
        'implementation ''org.springframework.boot:spring-boot-starter-batch'''),
       ('Validation', 'Bean Validation with Hibernate validator.', 'I/O',
        'implementation ''org.springframework.boot:spring-boot-starter-validation'''),
       ('Java Mail Sender', 'Send email using Java Mail and Spring Framework''s JavaMailSender.', 'I/O',
        'implementation ''org.springframework.boot:spring-boot-starter-mail'''),
       ('Quartz Scheduler', 'Schedule jobs using Quartz.', 'I/O',
        'implementation ''org.springframework.boot:spring-boot-starter-quartz'''),
       ('Spring Boot DevTools',
        'Provides fast application restarts, LiveReload, and configurations for enhanced development experience.',
        'DEVELOPER TOOLS', 'developmentOnly ''org.springframework.boot:spring-boot-devtools'''),
       ('Lombok', 'Java annotation library which helps to reduce boilerplate code.', 'DEVELOPER TOOLS',
        'compileOnly ''org.projectlombok:lombok''');